### PR TITLE
Deep object and array object mapping capabilities. ExpressionLanguage property access.

### PR DESCRIPTION
**Pull request by draco1989**
Features added to bundle:
- Added **ObjectMappingFilter**: Maps an object after source value extration
- Added **ArrayObjectMappingFilter**: Maps an array object after source value extration
- Added **Expression** field accessor: Source value retrieving using Symfony ExpressionLanguage

### CODE REVIEW

**Comment by draco1989** [comment]
If agree with the improvement, please merge and create new tag.

Thanks

**Comment by draco1989** [comment]
Please, I would thank you to merge or reject the pull request.

**Comment by draco1989** [comment]
Please review pull request.

**Comment by BenjaminPaap** [comment]
Testet everything. Great work. Sorry for the long delay.

**Pull request merged**
